# https://github.com/marketplace/actions/flawfinder-action
name: flawfinder
on: [push]

jobs:
  build:
    name: flawfinder-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flawfinder-action 
        uses: deep5050/flawfinder-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          report_type:
          data_only:
          never_ignore:
          false_positive:
          inputs_flag:
          dot_directories:
          allow_link:
